-- migrate:up

-- Step 6 schema additions. Extends the existing Step 3 model minimally —
-- no parallel structures where an existing table already fits (sources,
-- research_claims, research_claim_sources, approval_requests, cost_events,
-- provider_usage_events, channel_provider_settings all carry over
-- unchanged). See docs/architecture/research-pipeline.md.

-- sources.source_type: broadened from Step 3's generic media-type enum
-- to a source-authority-relevant classification. No data exists yet for
-- this project (Step 5 never wrote a sources row), so this is a clean
-- redefinition, not a data migration.
ALTER TABLE sources DROP CONSTRAINT IF EXISTS sources_source_type_check;
ALTER TABLE sources ADD CONSTRAINT sources_source_type_check CHECK (source_type IN (
  'primary_source', 'government', 'academic', 'official_company', 'industry_report',
  'reputable_news', 'expert_analysis', 'documentation', 'forum_community', 'social_media', 'unknown'
));
ALTER TABLE sources ALTER COLUMN source_type SET DEFAULT 'unknown';

-- Authority and relevance are deliberately separate scores (see
-- docs/architecture/research-pipeline.md#source-authority--relevance) —
-- authority_score already existed (Step 3); relevance_score is new.
ALTER TABLE sources ADD COLUMN relevance_score NUMERIC(5, 2) CHECK (relevance_score IS NULL OR relevance_score BETWEEN 0 AND 100);
ALTER TABLE sources ADD CONSTRAINT sources_authority_score_range CHECK (authority_score IS NULL OR authority_score BETWEEN 0 AND 100);

-- `provider` (Step 3) already means "which search/retrieval provider
-- found this source" — no rename needed, just documented here since
-- Step 6 is the first thing that populates it.
COMMENT ON COLUMN sources.provider IS 'The search/retrieval provider that returned this source (e.g. tavily) — not an LLM provider.';

-- research_claims already has classification/verification_status/
-- time_sensitive/conflicting exactly as Step 6 needs — no changes.

-- channel_budget_limits.limit_type: adds a research-stage ceiling,
-- reusing the existing hard/soft + warning-threshold machinery rather
-- than a new budgeting subsystem (see docs/architecture/research-pipeline.md#budget-preflight).
ALTER TABLE channel_budget_limits DROP CONSTRAINT IF EXISTS channel_budget_limits_limit_type_check;
ALTER TABLE channel_budget_limits ADD CONSTRAINT channel_budget_limits_limit_type_check
  CHECK (limit_type IN ('per_video', 'monthly_channel', 'research_stage'));

-- ============================================================
-- research_plans — versioned, one row per research attempt/revision.
-- Generated by an LLM but never trusted to invent facts: it identifies
-- what to look for, not answers.
-- ============================================================
CREATE TABLE research_plans (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id            UUID NOT NULL REFERENCES channels(id),
  content_project_id    UUID NOT NULL,
  workflow_run_id       UUID,
  revision              INTEGER NOT NULL CHECK (revision > 0),
  primary_question      TEXT NOT NULL,
  plan                  JSONB NOT NULL,
  provider              TEXT,
  model                 TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (id, channel_id),
  UNIQUE (content_project_id, revision),
  FOREIGN KEY (content_project_id, channel_id) REFERENCES content_projects (id, channel_id),
  FOREIGN KEY (workflow_run_id, channel_id) REFERENCES workflow_runs (id, channel_id)
);

CREATE INDEX idx_research_plans_project ON research_plans (content_project_id, revision DESC);

-- ============================================================
-- research_packages — versioned. Only narrative/synthesis fields live
-- in `synthesis`; claim/source lists are assembled live from the
-- relational tables at read time (get_current_research_package()) so
-- there is exactly one source of truth for "what claims/sources exist,"
-- never a JSONB copy that can drift from research_claims/sources.
-- ============================================================
CREATE TABLE research_packages (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id            UUID NOT NULL REFERENCES channels(id),
  content_project_id    UUID NOT NULL,
  workflow_run_id       UUID,
  research_plan_id      UUID,
  revision              INTEGER NOT NULL CHECK (revision > 0),
  revision_trigger      TEXT NOT NULL DEFAULT 'initial' CHECK (revision_trigger IN (
                          'initial', 'qc_auto_retry', 'human_revision_request'
                        )),
  revision_reason       TEXT,
  synthesis             JSONB NOT NULL,
  qc_score              NUMERIC(5, 2) CHECK (qc_score IS NULL OR qc_score BETWEEN 0 AND 100),
  qc_status             TEXT NOT NULL DEFAULT 'pending' CHECK (qc_status IN (
                          'pending', 'passed', 'revision_needed', 'failed'
                        )),
  qc_details            JSONB NOT NULL DEFAULT '{}'::jsonb,
  provider              TEXT,
  model                 TEXT,
  is_current            BOOLEAN NOT NULL DEFAULT false,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (id, channel_id),
  UNIQUE (content_project_id, revision),
  FOREIGN KEY (content_project_id, channel_id) REFERENCES content_projects (id, channel_id),
  FOREIGN KEY (workflow_run_id, channel_id) REFERENCES workflow_runs (id, channel_id),
  FOREIGN KEY (research_plan_id, channel_id) REFERENCES research_plans (id, channel_id)
);

-- Exactly one current version per project — enforced by the database,
-- not just by application discipline.
CREATE UNIQUE INDEX idx_research_packages_one_current_per_project
  ON research_packages (content_project_id) WHERE is_current;

CREATE INDEX idx_research_packages_project ON research_packages (content_project_id, revision DESC);

-- migrate:down

DROP TABLE IF EXISTS research_packages;
DROP TABLE IF EXISTS research_plans;
ALTER TABLE channel_budget_limits DROP CONSTRAINT IF EXISTS channel_budget_limits_limit_type_check;
ALTER TABLE channel_budget_limits ADD CONSTRAINT channel_budget_limits_limit_type_check
  CHECK (limit_type IN ('per_video', 'monthly_channel'));
ALTER TABLE sources DROP CONSTRAINT IF EXISTS sources_authority_score_range;
ALTER TABLE sources DROP COLUMN IF EXISTS relevance_score;
ALTER TABLE sources ALTER COLUMN source_type SET DEFAULT 'article';
ALTER TABLE sources DROP CONSTRAINT IF EXISTS sources_source_type_check;
ALTER TABLE sources ADD CONSTRAINT sources_source_type_check CHECK (source_type IN (
  'article', 'video', 'academic_paper', 'official_statement', 'social_post', 'dataset', 'other'
));
